version: '1.0.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
skip_tags: true
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
clone_depth: 1
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
test_script:
  # Run all tests
  - cmd: dotnet test --no-build --no-restore
build_script:
  # Build everything
  - cmd: dotnet build --no-restore
deploy:
  release: v$(appveyor_build_version)
  description: '{version}'
  provider: GitHub
  auth_token: 
    secure: pmrOSWJmxWC7kMbFK39zyTmJ3F3Vl9aX3nwExv+lTFcNdSyyMELuQkzoA0xIj2qc
  draft: false
  prerelease: false
environment:
  access_token:
    secure: pmrOSWJmxWC7kMbFK39zyTmJ3F3Vl9aX3nwExv+lTFcNdSyyMELuQkzoA0xIj2qc
  git_email:
    secure: 5EodxtRa6w7UZeb3SQhOIWhkaWTx6mIZ0S1TDe2Mp64=
#on_success:
#  - git config --global credential.helper store
#  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
#  - git config --global user.email "$($env:git_email)"
#  - git config --global user.name "James Woodley"
#  - git tag v$(version)
#  - git push --tags