// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N17Solutions.Semaphore.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace N17Solutions.Semaphore.Data.Migrations
{
    [DbContext(typeof(SemaphoreContext))]
    [Migration("20180913134124_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("N17Solutions.Semaphore.Domain.Model.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastUpdated");

                    b.Property<string>("Name");

                    b.Property<Guid>("ResourceId");

                    b.HasKey("Id");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("N17Solutions.Semaphore.Domain.Model.Signal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastUpdated");

                    b.Property<long?>("FeatureId");

                    b.Property<string>("Name");

                    b.Property<Guid?>("ResourceId");

                    b.Property<string>("Tags");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("Signal");
                });

            modelBuilder.Entity("N17Solutions.Semaphore.Domain.Model.Signal", b =>
                {
                    b.HasOne("N17Solutions.Semaphore.Domain.Model.Feature")
                        .WithMany("Signals")
                        .HasForeignKey("FeatureId");
                });
#pragma warning restore 612, 618
        }
    }
}
